3:
  ge: 0
  lt: 60000
  rate:
    pre_buy: 4.4
    up2:   3.8
    up1:  1.9
    eq:  0.2
    dw: 2.0
#4:
#  ge: 6000
#  lt: 12000
#  rate:
#    pre_buy: 4.1
#    up2:   3.
#    up1:  1.5
#    eq:  0.3
#    dw: 1.6
#5:
#  ge: 12000
#  lt: 0
#  rate:
#    pre_buy: 4.0
#    up2:   2.6
#    up1:  1.4
#    eq:  0.2
#    dw: 1.5
